maqueen.writeLED(maqueen.LED.LEDLeft, maqueen.LEDswitch.turnOn)
maqueen.writeLED(maqueen.LED.LEDRight, maqueen.LEDswitch.turnOn)
let strip = neopixel.create(DigitalPin.P15, 4, NeoPixelMode.RGB)
strip.setBrightness(20)
strip.setPixelColor(0, neopixel.colors(NeoPixelColors.Blue))
strip.setPixelColor(1, neopixel.colors(NeoPixelColors.Yellow))
strip.setPixelColor(2, neopixel.colors(NeoPixelColors.Red))
strip.setPixelColor(3, neopixel.colors(NeoPixelColors.Green))
strip.showRainbow(1, 360)
maqueen.servoRun(maqueen.Servos.S1, 360)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(500)
maqueen.motorRun(maqueen.Motors.M2, maqueen.Dir.CW, 50)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(500)
maqueen.motorRun(maqueen.Motors.M1, maqueen.Dir.CCW, 50)
maqueen.motorStop(maqueen.Motors.All)
basic.pause(500)
basic.forever(function () {
    strip.show()
    basic.pause(500)
    strip.rotate(1)
    strip.shift(1)
    music.playMelody("C D E F G A B C5 ", 120)
})
